apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: insecure-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-protocols: "TLSv1 TLSv1.1 TLSv1.2"
    nginx.ingress.kubernetes.io/ssl-ciphers: "HIGH:RSA+AES:3DES"
spec:
  rules: []
