[package]
name = "pqc_scan_detectors"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
regex.workspace = true
aho-corasick.workspace = true
x509-parser.workspace = true
pem.workspace = true
serde_json.workspace = true
tree-sitter.workspace = true
tree-sitter-go.workspace = true
tree-sitter-java.workspace = true
tree-sitter-javascript.workspace = true
tree-sitter-python.workspace = true
tree-sitter-rust.workspace = true
tree-sitter-ruby.workspace = true
pqc_scan_core = { path = "../pqc_scan_core" }
pqc_scan_rules = { path = "../pqc_scan_rules" }
